config/routes.rb
Rails.application.routes.draw do
  root 'products#shop'

  get 'shop', to: 'products#shop'
  get 'cart', to: 'cart#index'

  post 'add_to_cart', to: 'order_item#create'
  post 'update_cart', to: 'order_item#update'
  post 'remove_cart_item', to: 'order_item#destroy'

  get 'submit_order/step/:current_step', to: 'orders#submit', as: 'submit_order'
  patch 'submit_order/step/:current_step', to: 'orders#advance_step', as: 'advance_step'


  resources :orders
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    attr_accessor :current_step

    has_many :order_items, :dependent => :delete_all

    validates :name, presence: true, if: -> { is_step(1) }
    validates :street, presence: true, if: -> { is_step(1) }
    validates :zipcode, presence: true, 
                        :numericality => { :greater_than_or_equal_to => 0 },
                        if: -> { is_step(1) }
    validates :city, presence: true, if: -> { is_step(1) }
    validates :blz, presence: true, 
                    length: { minimum: 5 }, 
                    :numericality => { :greater_than_or_equal_to => 0 },
                    if: -> { is_step(2) }
    validates :account, presence: true,
                        length: { minimum: 10 },
                        :numericality => { :greater_than_or_equal_to => 0 },
                        if: -> { is_step(2) }

    def total
        total = 0

        self.order_items.each do |item|
            total += ( item.product.price ) * item.quantity
        end

        return total
    end

    def is_step(step)
        step == current_step or current_step == nil
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  validates :quantity, presence: true, :numericality => { :greater_than_or_equal_to => 0 }  

  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items, :dependent => :delete_all

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected
    def cart_order
        if session[:order_id]
          @order = Order.find_by_id(session[:order_id])
        end

        if @order.nil?
            @order = self.new_cart
        end

        return @order
    end

    def new_cart
        @order = Order.new
        @order.status = 'pending'
        @order.save(:validate => false)
        session[:order_id] = @order.id

        return @order
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    def index
        @order = cart_order
    end
end

app/controllers/order_item_controller.rb
class OrderItemController < ApplicationController
  def create
    @order = cart_order

    @order_item = @order.order_items.where('product_id': params[:order_item][:product_id]).first

    if @order_item
        quantity = @order_item.quantity + 1

        @order_item.update('quantity': quantity)
        @order_item.save
    else
        @order.order_items.new(order_items_params)
    end

    @order.save(:validate => false)

    redirect_to cart_path
  end

  def update
    if session[:order_id]
      @order = Order.find(session[:order_id])
      @order_item = OrderItem.find(params[:order_item][:id])

      if params[:order_item][:quantity] == '0'
        @order_item.destroy
        redirect_to cart_path
        return
      end

      @order_item.update(order_items_params)
    end 

    redirect_to cart_path
  end

  def destroy
    @order_item = OrderItem.find(params[:order_item][:id])
    @order_item.destroy
 
    redirect_to cart_path
  end


  private
    def order_items_params
        params.require(:order_item).permit(:product_id, :quantity)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where('status': 'completed').all
  end

  def create
    @order = Order.new(order_params)
 
    if @order.save
      redirect_to @order
    else
      render 'new'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
 
    redirect_to orders_path
  end

  def submit
    @order = cart_order

    if @order.order_items.count == 0
        redirect_to shop_path
    end
  end

  def advance_step
    @order = cart_order

    @order.current_step = params[:current_step].to_i
    @order.save

    if params[:current_step].to_i >= 3
        @order.status = 'completed'
        @order.save
        session[:order_id] = nil
        redirect_to orders_path
        return
    end

    next_step = params[:current_step].to_i + 1

    if @order.update(order_params)
      redirect_to submit_order_path(next_step)
    else
      render 'submit'
    end
  end

  private
    def order_params
      params.require(:order).permit(
        :street, 
        :city,
        :zipcode,
        :email,
        :name,
        :blz,
        :account
        )
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def shop
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
 
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])
 
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
 
    redirect_to products_path
  end
 
  private
    def product_params
      params.require(:product).permit(:title, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<h1 class="title">Warenkorb</h1>

<hr>

<table class="table">
    <thead>
        <tr>
            <th>Produkt</th>
            <th width="200">Anzahl</th>
            <th width="100"></th>
            <th>Preis</th>
            <th>Summe</th>
        </tr>
    </thead>
    <tbody>
        <% @order.order_items.each do |order_item| %>
            <tr>
                <td><%= order_item.product.title %></td>
                <td>
                    <%= form_for :order_item, url: update_cart_path do |form| %>
                        <%= form.hidden_field :id, value: order_item.id %>
                        <div class="level">
                            <%= form.number_field :quantity, value: order_item.quantity, :class => "input" %>
                            <%= form.submit 'Ändern', :class => "button is-link" %>
                        </div>
                    <% end %>
                </td>
                <td>
                    <%= form_for :order_item, url: remove_cart_item_path do |form| %>
                        <%= form.hidden_field :id, value: order_item.id %>
                        <div class="level">
                            <%= form.submit 'Entfernen', :class => "button is-link" %>
                        </div>
                    <% end %>
                </td>
                <td><%= order_item.product.price %></td>
                <td><%= order_item.product.price * order_item.quantity %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<% if @order.order_items.count > 0 %>

<div class="has-text-right"><strong>Summe:</strong> <%= @order.total %></div>

<%= link_to 'Bestellen', submit_order_path(1), :class => "button is-primary" %>

<% else %>

<p>Keine Produkte im Warenkorb</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav has-shadow">
      <div class="container">
        <div class="nav-left">
          <div class="nav-item">
            <h1 class="title">Shopper</h1>
          </div>
          <%= link_to 'Shop', shop_path, :class => "nav-item is-tab" %>
          <%= link_to 'Produktverwaltung', products_path, :class => "nav-item is-tab" %>
          <%= link_to 'Bestellungen', orders_path, :class => "nav-item is-tab" %>
        </div>
        <div class="nav-right">
          <%= link_to 'Warenkorb', cart_path, :class => "nav-item is-tab" %>
        </div>
      </div>
    </nav>

    <section class="section">
        <div class="container">
            <%= yield %>
        </div>
    </section>
  </body>
</html>

app/views/orders/_submit_step_1.html.erb
<%= form_for @order, url: advance_step_path(params[:current_step]) do |form| %>

<% if @order.errors.any? %>
  <div class="notification">
    <h2>
        <strong>Fehler</strong>
    </h2>
    <ul>
      <% @order.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :name, 'Vor- und Nachname', :class => "label" %>
  <p class="control">
    <%= form.text_field :name, :class => "input" %>
  </p>
</div>

<div class="field">
  <%= form.label :email, 'E-Mail Adresse', :class => "label" %>
  <p class="control">
    <%= form.text_field :email, :class => "input" %>
  </p>
</div>

<div class="field">
  <%= form.label :street, 'Straße', :class => "label" %>
  <p class="control">
    <%= form.text_field :street, :class => "input" %>
  </p>
</div>

<div class="field">
  <%= form.label :zipcode, 'Postleitzahl', :class => "label" %>
  <p class="control">
    <%= form.number_field :zipcode, :class => "input" %>
  </p>
</div>

<div class="field">
  <%= form.label :city, 'Ort', :class => "label" %>
  <p class="control">
    <%= form.text_field :city, :class => "input" %>
  </p>
</div>

<div class="field">
  <p class="control">
    <%= form.submit 'Weiter', :class => "button is-primary" %>
  </p>
</div>


<% end %>

app/views/orders/_submit_step_2.html.erb
<%= form_for @order, url: advance_step_path(params[:current_step]) do |form| %>

<% if @order.errors.any? %>
  <div class="notification">
    <h2>
        <strong>Fehler</strong>
    </h2>
    <ul>
      <% @order.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :blz, 'Bankleitzahl', :class => "label" %>
  <p class="control">
    <%= form.text_field :blz, :class => "input" %>
  </p>
</div>

<div class="field">
  <%= form.label :account, 'Kontonummer', :class => "label" %>
  <p class="control">
    <%= form.text_field :account, :class => "input" %>
  </p>
</div>

<div class="field">
  <p class="control">
    <%= form.submit 'Weiter', :class => "button is-primary" %>
  </p>
</div>


<% end %>

app/views/orders/_submit_step_3.html.erb
<%= form_for @order, url: advance_step_path(params[:current_step]) do |form| %>

<h3 class="subtitle">Bestelldaten</h3>

<table class="table">
  <tbody>
      <tr>
        <td>Kontaktdaten</td>
        <td>
          <%= @order.name %><br>
          <%= @order.email %>
        </td>
      </tr>
      <tr>
        <td>Adresse</td>
        <td><%= @order.street %>, <%= @order.zipcode %> <%= @order.city %></td>
      </tr>
      <tr>
        <td>Bankleitzahl</td>
        <td><%= @order.blz %></td>
      </tr>
      <tr>
        <td>Kontonummer</td>
        <td><%= @order.account %></td>
      </tr>
  </tbody>
</table>

<hr>

<h3 class="subtitle">Produkte</h3>

<table class="table">
  <thead>
    <tr>
      <th>Produkt</th>
      <th>Anzahl</th>
      <th>Preis</th>
    </tr>
  </thead>
  <tbody>
    <% @order.order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.product.title %></td>
        <td><%= order_item.quantity %></td>
        <td><%= order_item.product.price %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td>Summe: <%= @order.total %></td>
    </tr>
  </tbody>
</table>

<%= form.hidden_field :status, value: 'completed' %>

<div class="field">
  <p class="control">
    <%= form.submit 'Bestellung abschließen', :class => "button is-primary" %>
  </p>
</div>

<% end %>

app/views/orders/index.html.erb
<h1 class="title">Bestellungen</h1>

<hr>

<table class="table">
    <thead>
        <tr>
            <th>Bestellnummer</th>
            <th>Name</th>
            <th>Produkte</th>
            <th>Lieferadresse</th>
            <th>Bankdaten</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @orders.each do |order| %>
        <tr>
            <td><%= order.id %></td>
            <td>
                <%= order.name %><br>
                <%= order.email %>
            </td>
            <td>
                <% order.order_items.each do |order_item| %>
                  <%= order_item.product.title %><br>
                <% end %>
            </td>
            <td><%= order.street %>, <%= order.zipcode %> <%= order.city %></td>
            <td>
                BLZ: <%= order.blz %><br>
                KNr: <%= order.account %>
            </td>
            <td>
                <%= order.status %>
            </td>
            <td><%= link_to 'Löschen', order_path(order),
              method: :delete,
              data: { confirm: 'Sind Sie sicher?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<% if @orders.count == 0 %>
    Leider wurden keine Bestellungen gefunden
<% end %>

app/views/orders/submit.html.erb
<h1 class="title">Bestellung aufgeben</h1>
<h2 class="subtitle">Schritt <%= params[:current_step] %></h2>

<hr>

<%= render :partial => 'submit_step_' + params[:current_step] %>

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <div class="notification">
    <h2>
        <strong>Fehler</strong>
    </h2>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :title, 'Produkttitel', :class => "label" %>
  <p class="control">
    <%= form.text_field :title, :class => "input" %>
  </p>
</div>

<div class="field">
  <%= form.label :description, 'Produktbeschreibung', :class => "label" %>
  <p class="control">
    <%= form.text_area :description, :class => "textarea" %>
  </p>
</div>

<div class="field">
  <%= form.label :price, 'Preis', :class => "label" %>
  <p class="control">
    <%= form.text_field :price, :class => "input" %>
  </p>
</div>

app/views/products/edit.html.erb
<h1 class="title">Produkte</h1>
<h2 class="subtitle">"<%= @product.title %>" bearbeiten</h2>

<hr>

<%= form_for @product do |form| %>

<%= render :partial => 'form', :locals => {:form => form} %>

<div class="field">
  <p class="control">
    <%= form.submit 'Produkt anlegen', :class => "button is-primary" %>
  </p>
</div>


<% end %>

app/views/products/index.html.erb
<h1 class="title">Produkte <%= link_to 'Produkt anlegen', new_product_path, :class => "button is-primary" %></h1>

<hr>

<table class="table">
    <thead>
        <tr>
            <th>Produkt</th>
            <th>Beschreibung</th>
            <th>Preis</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @products.each do |product| %>
        <tr>
            <td><%= link_to product.title, product_path(product) %></td>
            <td><%= simple_format(product.description) %></td>
            <td><%= product.price %></td>
            <td><%= link_to 'Bearbeiten', edit_product_path(product) %></td>
            <td><%= link_to 'Löschen', product_path(product),
              method: :delete,
              data: { confirm: 'Sind Sie sicher?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<% if @products.count == 0 %>
    Leider wurden keine Produkte gefunden
<% end %>

app/views/products/new.html.erb
<h1 class="title">Produkte</h1>
<h2 class="subtitle">Produkt anlegen</h2>

<hr>

<%= form_for :product, url: products_path do |form| %>

<%= render :partial => 'form', :locals => {:form => form} %>

<div class="field">
  <p class="control">
    <%= form.submit 'Produkt anlegen', :class => "button is-primary" %>
  </p>
</div>


<% end %>

app/views/products/shop.html.erb
<h1 class="title">Shop</h1>

<hr>

<table class="table">
    <thead>
        <tr>
            <th>Produkt</th>
            <th>Beschreibung</th>
            <th>Preis</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @products.each do |product| %>
        <tr>
            <td><%= link_to product.title, product_path(product) %></td>
            <td><%= simple_format(product.description) %></td>
            <td><%= product.price %></td>
            <td>
                <%= form_for :order_item, url: add_to_cart_path do |form| %>
                    <%= form.hidden_field :product_id, value: product.id %>
                    <%= form.hidden_field :quantity, value: 1 %>
                    <%= form.submit 'In den Warenkorb', :class => "button is-link" %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<% if @products.count == 0 %>
    Leider wurden keine Produkte gefunden
<% end %>

app/views/products/show.html.erb
<h1 class="title"><%= @product.title %> <%= link_to 'Bearbeiten', edit_product_path(@product), :class => "button is-primary" %></h1>
<hr>
<div class="content">
    <p><strong>Beschreibung:</strong></p>
    <p><%= simple_format(@product.description) %></p>
</div>

<div class="content">
    <p><strong>Preis:</strong></p>
    <p>&euro; <%= @product.price %></p>
</div>

<%= form_for :order_item, url: add_to_cart_path do |form| %>
    <%= form.hidden_field :product_id, value: @product.id %>
    <%= form.hidden_field :quantity, value: 1 %>
    <%= form.submit 'In den Warenkorb', :class => "button is-primary" %>
<% end %>